name: 'Execute remote command'
description: 'Executes a remote command using SSH.'
inputs:
    remote_username:
        description: 'username'
        required: true
    remote_host:
        description: 'SFTP server hostname'
        required: true
    remote_port:
        description: 'SFTP server port, defaults to 22'
        required: true
        default: '22'
    remote_ssh_key:
        description: 'SSH private key'
        required: true
    remote_cmd:
        description: 'Command to execute on remote'
        required: true
        default: echo Hello

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.remote_username }}
        - ${{ inputs.remote_host }}
        - ${{ inputs.remote_port }}
        - ${{ inputs.remote_ssh_key }}
        - ${{ inputs.remote_cmd }}
