version: "3.8"

services:
  keycloak-db:
    container_name: keycloak-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: false
    tty: false
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-theRootPassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-kc_db}
      MYSQL_USER: ${MYSQL_USER:-kc_app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-KeycloakAppP*55w0rd}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT:-3333}
    ports:
       - ${MYSQL_TCP_PORT:-3333}:${MYSQL_TCP_PORT:-3333}
    volumes:
      - type: bind
        source: ${KC_DB_DATAFILES_DIR:-../../../keycloak-data-files}
        target: /var/lib/mysql
        read_only: false
      - type: bind
        source: ${MYSQL_DB_INIT_SCRIPT:-./initdb.sql}
        target: /docker-entrypoint-initdb.d/initdb.sql
        read_only: true
    healthcheck:
        test: "mysql $${MYSQL_DATABASE} -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --port=$${MYSQL_TCP_PORT} -e 'SELECT 1;'"
        timeout: 20s
        retries: 10
    networks:
    - kcnet

  keycloak-app:
    container_name: keycloak-app
    image: quay.io/keycloak/keycloak:23.0.3
    stdin_open: false
    tty: false
    environment:
      KC_HTTPS_CERTIFICATE_FILE: ${CERTIFICATE_FILE:-/certs/keycloak.crt}
      KC_HTTPS_CERTIFICATE_KEY_FILE: ${CERTIFICATE_KEY_FILE:-/certs/keycloak.key}
      KC_HTTPS_PORT: ${KC_HTTPS_PORT:-4499}
      KC_DB: ${KC_DB:-mysql}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST:-keycloak-db}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE:-kc_db}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-kc_app}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-KeycloakAppP*55w0rd}
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-IAmAnAdmin}
      KEYCLOAK_HTTPS_CLIENT_AUTH: none
      #KEYCLOAK_FRONTEND_URL: https://${KC_HOSTNAME:-localhost}:${KC_HTTPS_PORT:-4499}/auth
      #KEYCLOAK_FRONTEND_URL: https://localhost:4499/login/oauth2/code/policy-engine-ui
      KC_DB_URL_PORT: ${KC_DB_URL_PORT:-3333}
    networks:
      - kcnet
    volumes:
      - ${HOST_CERTIFICATE_FILE:-./certs/keycloak.crt}:${CERTIFICATE_FILE:-/certs/keycloak.crt}
      - ${HOST_CERTIFICATE_KEY_FILE:-./certs/keycloak.key}:${CERTIFICATE_KEY_FILE:-/certs/keycloak.key}
    ports:
      - ${KC_HTTPS_PORT:-4499}:${KC_HTTPS_PORT:-4499}
    command: ${KEYCLOAK_START_COMMAND:---verbose start-dev --hostname-port=${KC_HTTPS_PORT:-4499}}

    depends_on:
      keycloak-db:
         condition: service_healthy

networks:
  kcnet:
    name: db_kcnet
