version: "3.8"
services:
  policy-engine-api:
    container_name: policy-engine-api
    image: eclipse-temurin:21.0.1_12-jre
    command: java -jar /policy-engine-api/policy-engine-api.jar
    stdin_open: false
    tty: false
    environment:
      ENV_HTTPS_PORT: ${HTTPS_PORT:-9998}
      ENV_DB_HOST: ${DB_HOST:-policy-engine-db}
      ENV_DB_PORT: ${DB_PORT:-3311}
      ENV_DB_SCHEMA: ${DB_SCHEMA:-policy_engine_db}
      ENV_DB_USER: ${DB_USER:-policy_engine_db_user}
      ENV_DB_PASSWORD: ${DB_PASSWORD:-U5erPa55word}
      ENV_ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://localhost:9999}
      ENV_KEY_STORE_TYPE: ${KEY_STORE_TYPE:-pkcs12}
      ENV_KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD:-alligator*001}
      ENV_KEY_STORE: ${KEY_STORE:-/certs/keycloak.p12}

    ports:
      - ${HTTPS_PORT:-9998}:${HTTPS_PORT:-9998}
    volumes:
      - type: bind
        source: ${APP_JAR_FILEPATH:-../../../policy-engine-modules/policy-engine-api/target/policy-engine-api-0.0.1-SNAPSHOT.jar}
        target: /policy-engine-api/policy-engine-api.jar
        read_only: true
      - type: bind
        source: ${KEY_STORE_HOST_FILEPATH:-./certs/keycloak.p12}
        target: ${KEY_STORE:-/certs/keycloak.p12}
        read_only: true
    networks:
      - policyenginenet
      - db_policyenginenet

#    depends_on:
#      db_swot-db:
#        condition: service_healthy
#    restart: on-failure

networks:
  policyenginenet:
      
  db_policyenginenet:
    name: ${DB_DOCKER_NETWORK:-db_policyenginenet}
    external: true

