name: Create Policy-Engine-API Package

on:
 workflow_dispatch:
 
 pull_request:
  types: [opened, reopened, synchronize]
  branches:
    - "main"
  paths:
    - policy-engine-modules/policy-engine-api/** 
 push:
  branches:
    - "main"
  paths:
    - policy-engine-modules/policy-engine-api/**

 
jobs:
  get-release-type:
    runs-on: ubuntu-latest
    steps:
      - name: build-and-package
        id: build_package
        uses: mp30028/policy-engine/.github/actions/build-and-package/@main
        with:
          java-distribution: 'temurin'
          java-version: '21'
          application-name: 'policy-engine-api'
          source-location: 'policy-engine-modules/policy-engine-api'
          github-token: ${{ secrets.POLICY_ENGINE_WORKFLOWS_TOKEN }}

       